Fixing issue with build no finding the runtime
Need to add and lockdown to `"babel-plugin-transform-regenerator": "6.16.1",` per discussion in https://github.com/babel/babel/issues/4982#issuecomment-268625670

```
> spur-ioc@0.2.4 build /Users/acolchado/Code/opentable/npm/spur/spur-ioc
> babel src -d lib

node_modules/nan
resolve failed:  { Error: Cannot find module 'babel-runtime'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.requireRelative.resolve (/Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/require-relative/index.js:30:17)
    at resolve (/Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/modify-babel-preset/lib/serialize.js:83:11)
    at /Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/babel-core/lib/transformation/file/options/option-manager.js:302:17
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/babel-cli/lib/babel/util.js:50:22)
    at Object.compile (/Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/babel-cli/lib/babel/util.js:59:12)
    at write (/Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/babel-cli/lib/babel/dir.js:22:21)
    at handleFile (/Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/babel-cli/lib/babel/dir.js:44:7)
    at /Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/babel-cli/lib/babel/dir.js:63:11
    at arrayEach (/Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/lodash/lodash.js:9359:14)
    at /Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/babel-cli/lib/babel/dir.js:61:11
    at handle (/Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/babel-cli/lib/babel/dir.js:65:9)
    at arrayEach (/Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/lodash/lodash.js:9359:14)
    at module.exports (/Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/babel-cli/lib/babel/dir.js:72:7)
    at Object.<anonymous> (/Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/babel-cli/lib/babel/index.js:123:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/acolchado/Code/opentable/npm/spur/spur-ioc/node_modules/babel-cli/bin/babel.js:3:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3 code: 'MODULE_NOT_FOUND' } babel-runtime
```